// <auto-generated />
using System;
using ITAssetManagerLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITAssetManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420025622_ChangeServerDeviceDiskToString")]
    partial class ChangeServerDeviceDiskToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ITAssetManagerLibrary.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.CommonAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplyDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ManagementTag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OnSiteManager")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OnSiteManagerPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsibleCompany")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsiblePerson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsiblePersonPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CommonAssets");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Failure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisabilityHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("FailureDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ResolveDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResolveDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId");

                    b.ToTable("Failures");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ResolveDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId");

                    b.ToTable("Maintenances");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.MiscellaneousEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId")
                        .IsUnique();

                    b.ToTable("MiscellaneousEquipments");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.NetworkDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlashMemory")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("MainMemory")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<int>("NetworkEquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("OsVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("Rack")
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("UnitSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NetworkEquipmentId");

                    b.ToTable("NetworkDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.NetworkEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId")
                        .IsUnique();

                    b.ToTable("NetworkEquipments");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.RoutineCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId");

                    b.ToTable("RoutineChecks");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SecurityDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceSpec")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Rack")
                        .HasColumnType("longtext");

                    b.Property<int>("SecurityEquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("UnitSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SecurityEquipmentId");

                    b.ToTable("SecurityDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SecurityEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId")
                        .IsUnique();

                    b.ToTable("SecurityEquipments");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SecurityVulnerability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DiscoveryDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResolveDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TaskDetail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VulnerabilityDetail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId");

                    b.ToTable("SecurityVulnerabilities");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.ServerDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CpuClockGhz")
                        .HasColumnType("double");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("int");

                    b.Property<string>("Disk")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalDisk")
                        .HasColumnType("longtext");

                    b.Property<int?>("HbaCount")
                        .HasColumnType("int");

                    b.Property<string>("InternalDisk")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("MountedPhysicalServer")
                        .HasColumnType("longtext");

                    b.Property<string>("NetworkType")
                        .HasColumnType("longtext");

                    b.Property<int?>("NicCount")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("OsBit")
                        .HasColumnType("longtext");

                    b.Property<string>("OsType")
                        .HasColumnType("longtext");

                    b.Property<string>("OsVersion")
                        .HasColumnType("longtext");

                    b.Property<string>("Rack")
                        .HasColumnType("longtext");

                    b.Property<double?>("Ram")
                        .HasColumnType("double");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.ServiceLevelAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DisabilityHoursAverage")
                        .HasColumnType("double");

                    b.Property<int>("DisabilityHoursLevel")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDateOfMonth")
                        .HasColumnType("date");

                    b.Property<int>("RoutineCheckLevel")
                        .HasColumnType("int");

                    b.Property<double>("RoutineCheckRate")
                        .HasColumnType("double");

                    b.Property<int>("SecurityIssues")
                        .HasColumnType("int");

                    b.Property<int>("SecurityIssuesLevel")
                        .HasColumnType("int");

                    b.Property<double>("TechnicalSupportCompletionRate")
                        .HasColumnType("double");

                    b.Property<int>("TechnicalSupportLevel")
                        .HasColumnType("int");

                    b.Property<int>("UptimeLevel")
                        .HasColumnType("int");

                    b.Property<double>("UptimeRate")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("ServiceLevelAgreements");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId")
                        .IsUnique();

                    b.ToTable("Softwares");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SoftwareDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("ProgramName")
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftwareDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId")
                        .IsUnique();

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.StorageDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiskBackupInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PhysicalDiskInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("Rack")
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.ToTable("StorageDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SupportDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceSpec")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("SupportEquipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupportEquipmentId");

                    b.ToTable("SupportDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SupportEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommonAssetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonAssetId")
                        .IsUnique();

                    b.ToTable("SupportEquipments");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.UserAppointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllDay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RecurrenceRule")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAppointments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Failure", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithMany("Failures")
                        .HasForeignKey("CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Maintenance", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithMany("Maintenances")
                        .HasForeignKey("CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.MiscellaneousEquipment", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithOne("MiscellaneousEquipment")
                        .HasForeignKey("ITAssetManagerLibrary.Models.MiscellaneousEquipment", "CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.NetworkDevice", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.NetworkEquipment", "NetworkEquipment")
                        .WithMany("NetworkDevices")
                        .HasForeignKey("NetworkEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkEquipment");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.NetworkEquipment", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithOne("NetworkEquipment")
                        .HasForeignKey("ITAssetManagerLibrary.Models.NetworkEquipment", "CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.RoutineCheck", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithMany("RoutineChecks")
                        .HasForeignKey("CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SecurityDevice", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.SecurityEquipment", "SecurityEquipment")
                        .WithMany("SecurityDevices")
                        .HasForeignKey("SecurityEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityEquipment");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SecurityEquipment", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithOne("SecurityEquipment")
                        .HasForeignKey("ITAssetManagerLibrary.Models.SecurityEquipment", "CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SecurityVulnerability", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithMany("SecurityVulnerabilities")
                        .HasForeignKey("CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Server", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithOne("Server")
                        .HasForeignKey("ITAssetManagerLibrary.Models.Server", "CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.ServerDevice", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.Server", "Server")
                        .WithMany("ServerDevices")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Software", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithOne("Software")
                        .HasForeignKey("ITAssetManagerLibrary.Models.Software", "CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SoftwareDevice", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.Software", "Software")
                        .WithMany("SoftwareDevices")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Storage", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithOne("Storage")
                        .HasForeignKey("ITAssetManagerLibrary.Models.Storage", "CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.StorageDevice", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.Storage", "Storage")
                        .WithMany("StorageDevices")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SupportDevice", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.SupportEquipment", "SupportEquipment")
                        .WithMany("SupportDevices")
                        .HasForeignKey("SupportEquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportEquipment");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SupportEquipment", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Models.CommonAsset", "CommonAsset")
                        .WithOne("SupportEquipment")
                        .HasForeignKey("ITAssetManagerLibrary.Models.SupportEquipment", "CommonAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommonAsset");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.UserAppointment", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Data.ApplicationUser", "User")
                        .WithMany("UserAppointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITAssetManagerLibrary.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ITAssetManagerLibrary.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Data.ApplicationUser", b =>
                {
                    b.Navigation("UserAppointments");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.CommonAsset", b =>
                {
                    b.Navigation("Failures");

                    b.Navigation("Maintenances");

                    b.Navigation("MiscellaneousEquipment");

                    b.Navigation("NetworkEquipment");

                    b.Navigation("RoutineChecks");

                    b.Navigation("SecurityEquipment");

                    b.Navigation("SecurityVulnerabilities");

                    b.Navigation("Server");

                    b.Navigation("Software");

                    b.Navigation("Storage");

                    b.Navigation("SupportEquipment");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.NetworkEquipment", b =>
                {
                    b.Navigation("NetworkDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SecurityEquipment", b =>
                {
                    b.Navigation("SecurityDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Server", b =>
                {
                    b.Navigation("ServerDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Software", b =>
                {
                    b.Navigation("SoftwareDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.Storage", b =>
                {
                    b.Navigation("StorageDevices");
                });

            modelBuilder.Entity("ITAssetManagerLibrary.Models.SupportEquipment", b =>
                {
                    b.Navigation("SupportDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
